meta_product_name: "Sportify"
meta_title: "Sportify - find your perfect match! 🎾"
meta_description: "The app to find a sports partner, on your level, near you, today."
meta_image: "cover.png" # should exist in `app/assets/images/`
